import type { Category, Product } from './types';

export const CATEGORIES: Category[] = [
  { id: 'cat1', name: 'Perfumes' },
  { id: 'cat2', name: 'Accessories' },
  { id: 'cat3', name: 'Decor' },
  { id: 'cat4', name: 'Apparel' },
  { id: 'cat5', name: 'Stationery' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'prod1',
    name: 'Rose Perfume',
    price: 799,
    cost_price: 450,
    sku: 'RG-001',
    category_id: 'cat1',
    stock: 20,
    image_url: 'https://picsum.photos/seed/1/400/400',
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod2',
    name: 'Sandalwood Cologne',
    price: 899,
    cost_price: 500,
    sku: 'RG-002',
    category_id: 'cat1',
    stock: 15,
    image_url: 'https://picsum.photos/seed/2/400/400',
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod3',
    name: 'Vintage Pistol Decor',
    price: 4999,
    cost_price: 2500,
    sku: 'RG-003',
    category_id: 'cat3',
    stock: 5,
    image_url: 'https://picsum.photos/seed/3/400/400',
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod4',
    name: 'Silk Scarf',
    price: 1299,
    cost_price: 600,
    sku: 'RG-004',
    category_id: 'cat4',
    stock: 30,
    image_url: 'https://picsum.photos/seed/4/400/400',
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod5',
    name: 'Whiskey Glass Set',
    price: 2499,
    cost_price: 1200,
    sku: 'RG-005',
    category_id: 'cat2',
    stock: 12,
    image_url: 'https://picsum.photos/seed/5/400/400',
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod6',
    name: 'Leather Journal',
    price: 999,
    cost_price: 400,
    sku: 'RG-006',
    category_id: 'cat5',
    stock: 40,
    image_url: 'https://picsum.photos/seed/6/400/400',
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod7',
    name: 'Fountain Pen',
    price: 1999,
    cost_price: 950,
    sku: 'RG-007',
    category_id: 'cat5',
    stock: 25,
    image_url: 'https://picsum.photos/seed/7/400/400',
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod8',
    name: 'Designer Handbag',
    price: 8999,
    cost_price: 4500,
    sku: 'RG-008',
    category_id: 'cat2',
    stock: 8,
    image_url: 'https://picsum.photos/seed/8/400/400',
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod9',
    name: 'Premium Cigar Box',
    price: 3599,
    cost_price: 1800,
    sku: 'RG-009',
    category_id: 'cat2',
    stock: 18,
    image_url: 'https://picsum.photos/seed/9/400/400',
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod10',
    name: 'Scented Candle',
    price: 599,
    cost_price: 250,
    sku: 'RG-010',
    category_id: 'cat3',
    stock: 50,
    image_url: 'https://picsum.photos/seed/10/400/400',
    created_at: new Date().toISOString(),
  },
];
